### ISSUE TITLE
Can't run commands: Invalid arguments for function writefile

### ISSUE THREAD

**Issue by Groctel** [ledesmablt/vim-run#1]
I'm using neovim 0.4.4-1 and whenever I try to run a command (for example `RunSplit ruby main.rb` or simply `Run ls`) I get the following error:

```
Error detected while processing /home/groctel/.vim/plugged/vim-run/autoload/run.vim:
line   34:
E730: using List as a String
line   36:
E730: using List as a String
line   38:
E730: using List as a String
Error detected while processing function run#RunSplit[1]..run#Run:
line   59:
E15: Invalid expression: >split("\n"), currentcmdpath)
E116: Invalid arguments for function writefile
Press ENTER or type command to continue
```

**Comment by ledesmablt** [comment]
Looks like neovim doesn't support the arrow syntax for string/list/dict functions. This is one of the lines that's throwing the error. 

```vim
exec 'autocmd BufWinEnter ' . [editglob, sendglob, rundirglob]->join(',')
      \ . ' setlocal bufhidden=wipe'
```

Tried fixing it and your error went away, but there's a new error now (tested with nvim 0.4.4)

![image](https://user-images.githubusercontent.com/22242264/97705970-dbad3680-1aef-11eb-8b8f-da7a56a48efb.png)

The plugin depends on [vim's channels](https://vimhelp.org/channel.txt.html#job-start), which is [implemented differently in neovim](https://neovim.io/doc/user/eval.html#jobstart()).

I'll see what I can do to implement this fix. Would hate to exclude nvim users from using this :( thanks for raising this issue!

**Comment by ledesmablt** [comment]
Hey @Groctel , pushed [v1.0.2](https://github.com/ledesmablt/vim-run/releases/tag/v1.0.2) to partially address Neovim compatibility! Hope you could test it out and let me know if it works fine.

Unfortunately I couldn't figure out how to implement streaming stdout to a buffer, but you can still run and manage jobs. You can check out the docs [here](https://neovim.io/doc/user/channel.html) in case you'd like to try it out. Basically nvim is missing [these options](https://vimhelp.org/channel.txt.html#out_buf), so I can't find a straightforward way to implement it.

**Comment by Groctel** [comment]
Sorry for disappearing. I was packed with university obligations and didn't take care of my notifications. I tested it and works as intended. Thank you!
