### ISSUE TITLE
Awesome work

### ISSUE THREAD

**Issue by kkharji** [ledesmablt/vim-run#2]
I really liked how simple and strightforward the plugin is, well done. I wonder if there will be support for term-codes or at least strap it.

For now it would great if somehow the buffer filetype can be set to terminal through `setl filetype=terminal` plugins that support this can be activated on that buffer.

or perhaps make it optional 
https://github.com/ledesmablt/vim-run/blob/e7c5c6521d03b90bd7958d990f11208a78f93753/autoload/run.vim#L40-L41

Thanks a lot @ledesmablt

**Comment by ledesmablt** [comment]
Thank you for your comments! I believe vim doesn't have a `terminal` filetype that can support the term-codes. I've tried working around this before to get colors to work but couldn't come up with anything. Neovim also shares this issue when running bang commands (discussed [here](https://github.com/neovim/neovim/issues/1496)).

I guess to make the log file look prettier, the term-codes could be removed through regex or something. If you really need colors with your command output, I don't see any other way than running them through the terminal.
